### PR TITLE
Make shoutouts LOGGED_IN access

### PR DESCRIPTION
**Pull request by mrclay**

### CODE REVIEW

**Comment by mrclay** [comment]
I think the UI will get another update later and we might add the typical input/access dropdown then.

**Comment by kevinjardine** [comment]
It's just as easy for me to add the access drop down now. It would default to the standard system wide default access level, which I would prefer to do as it makes the plugin more flexible. Would that be OK?

**Comment by mrclay** [comment]
That's fine though we might hide it with CSS on our end until we figure out an ideal placement (I think the attach and Post buttons will be reversed). If the SELECT doesn't submit, set it to the site default.

**Comment by kevinjardine** [comment]
Fixed, with the default access level on my live development site set to logged_in so you can see how it works.

**Pull request closed without merging**
